### ISSUE TITLE
uflash broken

### ISSUE THREAD

**Issue by randomidiot69** [dobbelina/repository.dobbelina#1170]
uflash just show Catagories & Search
but no videos.

using android (ccwgtv) and kodi 20.2
[here is the log](https://paste.kodi.tv/kuyacadunu)

**Comment by dobbelina** [comment]
[Fixed](https://github.com/dobbelina/repository.dobbelina/commit/7ff372187d230f5f7168d0174650c9f4ae7eff53), will be in the next release.

**Comment by randomidiot69** [comment]
the Catagories & Search are fixed now BUT
cant play video and the video thumbnails are broken.

(using the latest version from the master.zip)

[the log](https://paste.kodi.tv/pejekekuta)

**Comment by 12asdfg12** [comment]
Probably the playback issue was related to Android (playback was working on Windows/ Linux) and was fixed by [e784f5b] (not tested).
The thumbnails are not loading because the image URLs from the website expire before Kodi can load all the images. This is not fixed.

**Comment by brainwaster** [comment]
Uflash is broken again, says Oh Oh, No videos found
