### ISSUE TITLE
MFC misdirecting

### ISSUE THREAD

**Issue by wwilesco** [dobbelina/repository.dobbelina#156]
In the last few days MFC directs you to a page with the same name as the one you entered but it is a completely different person. Happens with both Windows and Android. 
Also the mark as watched no longer works

**Comment by onknight** [comment]
had the same problem also  it not  connecting at all in some rooms

**Comment by ahminelli** [comment]
Been having that same issue for at least 2 weeks. Never even close to being who you click on.

**Comment by penguinfarms** [comment]
Same issue here when I select a model it takes me to a different one.  tried it on multiple kodi devices.

**Comment by frankee123** [comment]
Yes I have same issue. Please fix!

**Comment by onknight** [comment]
Fixed Tested on Windows Kodi Working ..

**Comment by wwilesco** [comment]
Thank you onknight. It is now working properly, you guys who keep UWC going are fantastic.

**Comment by onknight** [comment]
I just tested the fix  credit goes to those who made it

**Comment by ahminelli** [comment]
It's not fixed on my kodi. I get some models that are right, but mostly not even close. That is unless these models have been replaced using their names?
--
Sent from Outlook Email App for Android Monday, 27 January 2020, 04:50PM -06:00 from onknight  notifications@github.com :

**Comment by onknight** [comment]
I not had any problems delete the addon and reinstall it 
try that It work flawlessly for me I am using Kodi on a PC
