### ISSUE TITLE
Beeg

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#306]
Nothing loads up when u click on any video can u have a look

**Comment by dobbelina** [comment]
Works for me on Windows platform.

**Comment by deanogers** [comment]
Doesn’t work on kodi m8

**Comment by DJMix-I-Can** [comment]
It's working in Kodi, on Android & Windows.

**Comment by deanogers** [comment]
Won’t load any videos when u click on them nothing happens tried all different ones

**Comment by rogahn-boo** [comment]
I am with deanogers on this. 
Tried both, Android and Macos and play/download fails. 
To make sure, installed a fresh Kodi / UWC on Android and keeps falling

**Comment by jdoedev123** [comment]
Sorta works for me a Linux workstation running Kodi 18.6 and UWC 1.2.28. Videos play ok but the Video Names are not all displayed some are blank with just the time displayed.

**Comment by sallymartin13** [comment]
Latest Kodi & UWC installed on Android, nothing else, log file as follows:

ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-24 09:51:18.219 T:27447   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.uwc/?url=https%3A%2F%2Fbeeg.com%2Fapi%2Fv6%2F%2Fvideo%2F1895221153%3Fv%3D2&mode=82&name=Romantic+hotel+sex%5BCOLOR+deeppink%5D+15%3A30%5B%2FCOLOR%5D]
2020-10-24 09:51:21.555 T:27787   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-24 09:51:21.844 T:27447   ERROR: Playlist Player: skipping unplayable item: 1, path [plugin://plugin.video.uwc/?url=https%3A%2F%2Fbeeg.com%2Fapi%2Fv6%2F%2Fvideo%2F1456527796%3Fv%3D2&mode=82&name=Guy+gets+caught+in+the+act+and+turns+female+on%5BCOLOR+deeppink%5D+17%3A10%5B%2FCOLOR%5D]
2020-10-24 09:51:25.069 T:27792   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-24 09:51:25.286 T:27447   ERROR: Playlist Player: skipping unplayable item: 2, path [plugin://plugin.video.uwc/?url=https%3A%2F%2Fbeeg.com%2Fapi%2Fv6%2F%2Fvideo%2F1778261952%3Fv%3D2&mode=82&name=Russian+teacher+sedusing+you+and+talking%5BCOLOR+deeppink%5D+10%3A55%5B%2FCOLOR%5D]
2020-10-24 09:51:28.686 T:27797   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-24 09:51:28.979 T:27447   ERROR: Playlist Player: skipping unplayable item: 3, path [plugin://plugin.video.uwc/?url=https%3A%2F%2Fbeeg.com%2Fapi%2Fv6%2F%2Fvideo%2F1356810055%3Fv%3D2&mode=82&name=Omg+wake+up+bro%5BCOLOR+deeppink%5D+11%3A12%5B%2FCOLOR%5D]
2020-10-24 09:51:32.397 T:27803   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-24 09:51:32.688 T:27447   ERROR: Playlist Player: skipping unplayable item: 4, path [plugin://plugin.video.uwc/?url=https%3A%2F%2Fbeeg.com%2Fapi%2Fv6%2F%2Fvideo%2F1899405399%3Fv%3D2&mode=82&name=Two+nights+of+threesome+debauchery%5BCOLOR+deeppink%5D+12%3A17%5B%2FCOLOR%5D]
2020-10-24 09:51:36.746 T:27808   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-24 09:51:37.016 T:27447   ERROR: Playlist Player: skipping unplayable item: 5, path [plugin://plugin.video.uwc/?url=https%3A%2F%2Fbeeg.com%2Fapi%2Fv6%2F%2Fvideo%2F1169671038%3Fv%3D2&mode=82&name=Pussy+and+ass+big+toy+fuck%5BCOLOR+deeppink%5D+11%3A15%5B%2FCOLOR%5D]
2020-10-24 09:51:42.814 T:27447  NOTICE: CWinSystemAndroid::DestroyWindow
2020-10-24 09:57:34.727 T:27293 WARNING: CPeripheralBusAndroid: failed to update input device with ID 4 because it couldn't be found
2020-10-24 09:57:34.727 T:27293 WARNING: CPeripheralBusAndroid: failed to update input device with ID 5 because it couldn't be found
2020-10-24 09:57:34.728 T:27293 WARNING: CPeripheralBusAndroid: failed to update input device with ID 8 because it couldn't be found

**Comment by jdoedev123** [comment]
Ok tried and failed to play on Android 7.0 running UWC 1.2.28. 
Also tried to curl https://beeg.com on my Server and it failed with an expired SSL Certificate but worked on my Workstation.

I was wondering if this is related to some SSL Certificates that expired. I had a similar problem in UWC on Linux some months ago which I fixed by fiddling with the Certificates on the Workstation. A tool over at https://www.immuniweb.com/ssl/ shows that beeg.com is relying on some expired SSL Certificates namely "AddTrust External CA RootRoot CA" and "COMODO RSA Certification Authority" which expired in May 2020.

This appears to be a problem with the server configuration. I don't know a work around for an Android client.

**Comment by DJMix-I-Can** [comment]
I use the Nvidia shield with Android 9, Kodi 18.8, UWC 1.2.28 & Windows 7, Kodi 18.8 & UWC 1.2.28. Beeg works fine. As for some videos only showing the video duration time, that's how it is on their website. It's working fine on my end.

**Comment by DJMix-I-Can** [comment]
Guys, 18.9 just came out & addresses this issue, "Work around third-party changes to HTTP2 and SSL/encryption that impacted internet access from Kodi by scrapers, streaming addons, etc." Try that out & see if that fixes your problem. You could read about it [here.](https://kodi.tv/article/kodi-leia-189-release)

**Comment by deanogers** [comment]
No still won’t play anything updated to 18.9 nothing plays won’t load anything up

**Comment by lance77tour** [comment]
how come when you search not just in BEEG, the results are null or they pull a combination of results i.e. Janice Griffith it pulls Janice Griffith/ Janice/ Griffith/ other vids that aren't part of search?

**Comment by jdoedev123** [comment]
Took a look at the Beeg code in UWC. In Beeg search is actually searching for a Tag. If the Tag exists you should get a result but not necessarily what you anticipated.  The website allows for a Tag or "People" search.  I am thinking of separating into a SearchTag and a SearchPerson.

**Comment by lance77tour** [comment]
Just the other day I tried again.

Search:

Sandee
Westgate
Sandee Westgate

All came back with the “…”

[cid:image002.png@01D6B61C.706DC570]

**Comment by nedra089787** [comment]
Hi guys,
Yesterday's fix from camil fixes Beeg play & download on my Android 7. 
Thanks & great job

**Comment by jdoedev123** [comment]
Ok, I might have to wait until any other fixes are incorporated to post a fix for Search. My Beeg code has deviated from the standard as I test different updates.

**Comment by imurreflection** [comment]
Hi @jdoedev123. Please please please take a look at javhoho.com also

**Comment by dobbelina** [comment]
camilt has updated the scraper, thanks for the contribution!
Fix #314

**Comment by imurreflection** [comment]
@camilt...thank you so much for javhoho fix. It's highly appreciated...

**Comment by lance77tour** [comment]
Hello,

? What’s up with about 90% of Thumbnails missing in StreamXXX?

[cid:image001.png@01D6C1B2.3F58C510]

From: keith pillsbury
Sent: Sunday, November 8, 2020 10:14 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Just the other day I tried again.

Search:

Sandee
Westgate
Sandee Westgate

All came back with the “…”

[cid:image002.png@01D6C1B2.3F58C510]

**Comment by lance77tour** [comment]
Hi,

I saw you’ve done some stuff in add-on settings. So, I changed the following:

Scenes:                latest
Movies:                date
Upload date:      year
Duration:             long (20+m)
Quality:                no

And this is what it came back with.

[cid:image001.png@01D6CA91.4667BA40]

From: keith pillsbury
Sent: Monday, November 23, 2020 4:05 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Hello,

? What’s up with about 90% of Thumbnails missing in StreamXXX?

[cid:image001.png@01D6CA91.4667BA40]

From: keith pillsbury
Sent: Sunday, November 8, 2020 10:14 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Just the other day I tried again.

Search:

Sandee
Westgate
Sandee Westgate

All came back with the “…”

[cid:image002.png@01D6CA91.4667BA40]

**Comment by lance77tour** [comment]
And there’s a CAPTCHA

[cid:image001.png@01D6CA92.0AE60110]

From: keith pillsbury
Sent: Friday, December 4, 2020 11:03 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Hi,

I saw you’ve done some stuff in add-on settings. So, I changed the following:

Scenes:                latest
Movies:                date
Upload date:      year
Duration:             long (20+m)
Quality:                no

And this is what it came back with.

[cid:image001.png@01D6CA92.0AE60110]

From: keith pillsbury
Sent: Monday, November 23, 2020 4:05 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Hello,

? What’s up with about 90% of Thumbnails missing in StreamXXX?

[cid:image001.png@01D6CA92.0AE60110]

From: keith pillsbury
Sent: Sunday, November 8, 2020 10:14 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Just the other day I tried again.

Search:

Sandee
Westgate
Sandee Westgate

All came back with the “…”

[cid:image002.png@01D6CA92.0AE60110]

**Comment by lance77tour** [comment]
Sorry, Models for new PeekVids are only showing UWC Logo.

[cid:image001.png@01D6CA92.AD7A2EB0]

From: keith pillsbury
Sent: Friday, December 4, 2020 11:06 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

And there’s a CAPTCHA

[cid:image001.png@01D6CA92.AD7A2EB0]

From: keith pillsbury
Sent: Friday, December 4, 2020 11:03 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Hi,

I saw you’ve done some stuff in add-on settings. So, I changed the following:

Scenes:                latest
Movies:                date
Upload date:      year
Duration:             long (20+m)
Quality:                no

And this is what it came back with.

[cid:image001.png@01D6CA92.AD7A2EB0]

From: keith pillsbury
Sent: Monday, November 23, 2020 4:05 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Hello,

? What’s up with about 90% of Thumbnails missing in StreamXXX?

[cid:image001.png@01D6CA92.AD7A2EB0]

From: keith pillsbury
Sent: Sunday, November 8, 2020 10:14 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Just the other day I tried again.

Search:

Sandee
Westgate
Sandee Westgate

All came back with the “…”

[cid:image002.png@01D6CA92.AD7A2EB0]

**Comment by lance77tour** [comment]
Hi,

? How can I get the Thumbnails using the WALL View to not be so big? They’re much larger then UW’s.

[cid:image001.png@01D6F113.A19A3980]

From: keith pillsbury
Sent: Friday, December 4, 2020 11:11 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Sorry, Models for new PeekVids are only showing UWC Logo.

[cid:image001.png@01D6F113.A19A3980]

From: keith pillsbury
Sent: Friday, December 4, 2020 11:06 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

And there’s a CAPTCHA

[cid:image001.png@01D6F113.A19A3980]

From: keith pillsbury
Sent: Friday, December 4, 2020 11:03 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Hi,

I saw you’ve done some stuff in add-on settings. So, I changed the following:

Scenes:                latest
Movies:                date
Upload date:      year
Duration:             long (20+m)
Quality:                no

And this is what it came back with.

[cid:image001.png@01D6F113.A19A3980]

From: keith pillsbury
Sent: Monday, November 23, 2020 4:05 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Hello,

? What’s up with about 90% of Thumbnails missing in StreamXXX?

[cid:image001.png@01D6F113.A19A3980]

From: keith pillsbury
Sent: Sunday, November 8, 2020 10:14 PM
To: dobbelina/repository.dobbelina <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: RE: [dobbelina/repository.dobbelina] Beeg (#306)

Just the other day I tried again.

Search:

Sandee
Westgate
Sandee Westgate

All came back with the “…”

[cid:image002.png@01D6F113.A19A3980]
